collections:
  authors:
    output: true

defaults:
  - scope:
      path: 
      type: "authors"
    values:
      layouts: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
baseurl: /landing-page
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag