collections:
  authors:
    output: true

defaults:
  - scope:
      path: "blog"
      type: "authors"
    values:
      layouts: "author"
  - scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "blog"
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag